// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateEmailVerifyToken(ctx context.Context, arg CreateEmailVerifyTokenParams) (EmailVerificationToken, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetActiveEmailVerifyToken(ctx context.Context, token string) (EmailVerificationToken, error)
	GetActivePasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error)
	GetEmailVerifyToken(ctx context.Context, token string) (EmailVerificationToken, error)
	GetPasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, username string) (User, error)
	IsUserEmailVerified(ctx context.Context, username string) (bool, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	LocateUser(ctx context.Context, email string) (User, error)
	UpdateEmailVerifyToken(ctx context.Context, token string) error
	UpdatePasswordResetToken(ctx context.Context, token string) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
